---
title: "Comparing ISN To Radio Flux"
subtitle: "Jan. 1951 - Dec. 2019"
author: "David J Jackson"
date: "1/10/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.table)
library(lubridate)
library(plotly)
library(prophet)
```
```{r Import Radio Flux Date, echo=FALSE}
rm(list=ls())
F30 <-fread("./F107_F30.csv")
summary(F30)

colnames(F30) <- c("JD","Year","Month","Day", "F10_7","F30_R" )
F30$Ymd <- as.Date(paste(F30$Year, F30$Month, F30$Day, sep = "-"))
# F301<-F30[Ymd>="1964-07-01",.(Ymd,F10_7),]
F301<-F30[Ymd>="1951-01-01",.(Ymd,F10_7),]
F301$Vote <- ifelse(F301$F10_7 >=121.5,"Yes","No")
Fit <- as.data.frame(lowess(F301$F10_7,f=0.1))
F301 <-cbind(F301,Fit$y)
colnames(F301) <-c("Ymd","F10_7","Vote","Loess")
ggplot(data=F301,aes(x=Ymd,y=F10_7)) +geom_line() + ggtitle("Radio Flux F19_7: 1951 - 2019")
```

```{r Import Kaznel Daily ISN, echo=FALSE}
kanzel <- fread("./kh_spots.csv")
kanzel$Ymd <- as.Date(kanzel$Ymd)
kanzel$Vote <- ifelse(kanzel$R >=mean(kanzel$R),"Yes","No")
df1 <- kanzel[Ymd>="1951-01-01",.(Ymd,R)]
colnames(df1) <-c("ds","y" )
ggplot(data=df1,aes(x=ds,y=y)) + geom_line() + 
  ggtitle("Kanzel Daily ISN: 1951 - 2019") + xlab("Date/Year") + ylab("Daily  ISN")
```
```{r 365 Day Moving Average,echo=FALSE}
library(forecast)
F301$Ma <- ma(F301$F10_7,order=365)
df1$Ma <- ma(df1$y,order=365)
ggplot(data=F301,aes(x=Ymd,y=Ma,col="F10_7")) + geom_line() +
geom_line(data=df1,aes(x=ds,y=Ma,col="ISN")) + 
  ggtitle("Kanzel/Radio Flux 365 Day Moving Average") +
  xlab("Year/Day") + ylab("Moving Average")
```
```{r Predict Daily Radio Flux}
df <- F301 %>% select(Ymd,F10_7)
colnames(df) <- c("ds","y")
m <- prophet(seasonality.mode="multiplicative")
m <- add_seasonality(m, name="cycle_11year", period=364.25 * 11,fourier.order=5)
m <- fit.prophet(m, df)
future <- make_future_dataframe(m,periods=8000,freq="day")
forecast <- predict(m, future)
plot(m, forecast) +ggtitle("F10_7 Daily: Jan. 1951 - Dec. 2019") +ylab("Predicted Days w/ F10_7") +
  xlab("Years" ) 
```
```{r Predict Kanzel Daily ISN}
df1 <- kanzel[Ymd>="1951-01-01",.(Ymd,R)]
colnames(df1) <-c("ds","y")
m <- prophet(seasonality.mode="multiplicative")
m <- add_seasonality(m, name="cycle_11year", period=364.25 * 11,fourier.order=5)
m <- fit.prophet(m, df1)
future1 <- make_future_dataframe(m,periods=8000,freq="day")
forecast1 <- predict(m, future)
plot(m, forecast1) +ggtitle("Kanzel ISN : Jan. 1951 - Dec. 2019") +ylab("Predicted ISN") +
  xlab("Years" ) 
```
```{r}
df.isn <- as.data.table(forecast1)
df.isn <- df.isn[ds >="2020-01-01" & ds <="2025-12-31",]
df.flux <- as.data.table(forecast)
df.flux <- df.flux[ds >="2020-01-01" & ds <="2025-12-31",]

ggplot(data=df.isn,aes(x=ds,y=yhat,col="ISN")) + geom_line() + geom_smooth(method="glm") +
  ggtitle("Comparing ISN/Radio Flux: 2020 2026") + geom_line(data=df.flux,aes(x=ds,y=yhat,col="F10_7")) +
  xlab("Date/Year") +ylab("Predicted Values")

```
```{r imput values}
FDate <- seq(as.Date("1944-05-28"),as.Date("1953-12-31"),by="days")
FDATE <- as.data.table(FDate)
FDATE$F10_7 <- 0
A <- kanzel[Ymd <="1953-12-31",.(Ymd,R)]
A$F10_7 <- A$R *0.757
A <- A[,.(Ymd,F10_7)]
B <-F301[,.(Ymd,F10_7)]
C <- rbind(A,B)
ggplot(C) + geom_line(aes(x=Ymd,y=F10_7)) +
  labs(title="Radio Flux for F10_7 1944 - 2019",subtitle="Includes Imputed data from 1944 - 1954")
  
```


```{r Filling in missing values}
df.seq <- C %>% select(Ymd,F10_7)
colnames(df.seq) <- c("ds","y")
m <- prophet(seasonality.mode="multiplicative")
m <- add_seasonality(m, name="cycle_11year", period=364.25 * 11,fourier.order=5)
m <- fit.prophet(m, df.seq)
future3 <- make_future_dataframe(m,periods=8000,freq="day")
forecast3 <- predict(m, future3)
plot(m, forecast3) +ggtitle("F10_7 Daily: Jan. 1944 - Dec. 2019") +ylab("Predicted Days w/ F10_7") +
  xlab("Years" ) 
```